
name: Release
on:
  push:
    branches:
      - master
      - next
      - beta
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      LIBRARY_DIST_PATH: ./dist/abstract
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci

      - name: Test Library
        run: |
          npm run lint

      - name: Build library
        run: npm run build

      - name: Release
        if: success()
        run: |
          mv README.md $LIBRARY_DIST_PATH/README.md
          npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
