
name: Release
on:
  push:
    branches:
      - master
      - next
      - beta
      - "*.x"
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: |
          npm install --no-package-lock
          npm run build
      - run: npm run semantic-release
        env: 
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
